#!/usr/bin/env python3
"""Clean autogenerated ESP-IDF project files"""

import argparse
from pathlib import Path
import shutil

DEFAULT_DELETE = ["build", "build.clang", "managed_components", ".cache"]
FORCE_DELETE = ["sdkconfig", "sdkconfig.old"]


def main():
    parser = argparse.ArgumentParser(
        "clean.py",
        description="Clean auto generated files of an ESP-IDF project. Must be run in the root of said project.",
    )
    parser.add_argument(
        "-f",
        "--force",
        default=False,
        help="Whether to delete additional files which *could* result in data loss.",
        action="store_true",
    )
    parser.add_argument(
        "-d", "--dry-run",  default=False, action="store_true"
    )
    args = parser.parse_args()

    def process(path: Path):
        if path.exists():
            is_dir = path.is_dir()
            print(f"Deleting {'dir' if is_dir else 'file'}: {path}")
            if not args.dry_run:
                if is_dir:
                    shutil.rmtree(path)
                else:
                    path.unlink()

    if args.dry_run:
        print("**DRY RUN** (not actually deleting files/dirs)")

    for txt in DEFAULT_DELETE:
        process(Path(txt))
    for txt in FORCE_DELETE:
        process(Path(txt))

    print("**DONE**")


if __name__ == "__main__":
    main()
