#!/usr/bin/env python3
"""Clean autogenerated ESP-IDF project files"""

import argparse
import logging
from pathlib import Path
import shutil

from _project_cli import (
    add_common_logging_arg,
    add_project_arg,
    resolve_project_paths,
    setup_logging,
)

DEFAULT_DELETE = [
    "build",
    "build.clang",
    "managed_components",
    ".cache",
    ".serial_port",
]
FORCE_DELETE = ["sdkconfig", "sdkconfig.old"]


def main():
    parser = argparse.ArgumentParser(
        "clean.py",
        description=(
            "Clean auto-generated files of ESP-IDF project(s). "
            "Without -p/--project: repo root targets all projects, project root targets itself."
        ),
    )
    add_project_arg(parser)
    add_common_logging_arg(parser)
    parser.add_argument(
        "-f",
        "--force",
        default=False,
        help="Whether to delete additional files which *could* result in data loss.",
        action="store_true",
    )
    parser.add_argument("-d", "--dry-run", default=False, action="store_true")
    args = parser.parse_args()
    setup_logging(args.verbose)

    projects = resolve_project_paths(
        raw_project_values=args.project,
        single_project_only=False,
        operation_name="clean",
    )

    delete_list = list(DEFAULT_DELETE)
    if args.force:
        delete_list.extend(FORCE_DELETE)

    def process(path: Path):
        if path.exists():
            is_dir = path.is_dir()
            logging.info("Deleting %s: %s", "dir" if is_dir else "file", path)
            if not args.dry_run:
                if is_dir:
                    shutil.rmtree(path)
                else:
                    path.unlink()
        else:
            logging.debug("Skipping missing path: %s", path)

    if args.dry_run:
        logging.info("Dry-run mode enabled; no files will be deleted.")

    for project in projects:
        logging.info("[%s] Cleaning project artifacts.", project.name)
        for txt in delete_list:
            process(project / txt)

    logging.info("Clean operation complete.")


if __name__ == "__main__":
    main()
